import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

/*
  The metadata is rendered in the metadata of the home page. 
  The page is given a title and description.
*/
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/*
  The root layout shows UI that is shared across multiple routes.
  On navigation, layouts preserve state, remain interactive, and do not re-render. 
  Layouts can also be nested.
  The root layout applies to all routes. It is required and must contain the <html> and <body> tags.
  This layout will wrap layouts at lower parts of the folders structure.
  When a layout and a page are defined in the same folder, the layout wraps the page.
*/
export default function RootLayout({
  // The children prop is populated with a child layout if it exists or a page during rendering.
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Include shared UI here e.g. a header or sidebar */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
